services:
  - type: web
    name: soulsync-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JIOSAAVN_API
        value: https://saavn.sumit.co/api
      - key: BACKEND_URL
        value: https://soulsync-backend-a5fs.onrender.com
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: soulsync-backend
          property: host
